## Buổi 03: Phân tích dữ liệu với Python

In [23]:
# !rm -r pydata-book
# !git clone https://github.com/wesm/pydata-book.git
!ls pydata-book/
# !sudo rm -r pydata-book/.git

COPYING     ch02.ipynb	ch06.ipynb  ch10.ipynb	datasets
README.md   ch03.ipynb	ch07.ipynb  ch11.ipynb	examples
appa.ipynb  ch04.ipynb	ch08.ipynb  ch12.ipynb	requirements.txt
appb.ipynb  ch05.ipynb	ch09.ipynb  ch13.ipynb


In [24]:
!git status

On branch gh-pages
Your branch is up to date with 'origin/gh-pages'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    ../buoi02_250816/.ipynb_checkpoints/Untitled-checkpoint.ipynb
	deleted:    ../buoi02_250816/.ipynb_checkpoints/ex1_calc-checkpoint.py
	deleted:    ../buoi02_250816/.ipynb_checkpoints/first-checkpoint.py
	deleted:    ../buoi02_250816/Untitled.ipynb
	deleted:    ../buoi02_250816/ex1_calc.py
	deleted:    ../buoi02_250816/ex2_scientific1.ipynb
	deleted:    ../buoi02_250816/ex2_scientific1.txt
	deleted:    ../buoi02_250816/ex4_scientific2.txt
	deleted:    ../buoi02_250816/first.py
	deleted:    ../buoi03_250819/.ipynb_checkpoints/python101_ST3-checkpoint.ipynb
	deleted:    ../buoi03_250819/first.cpp
	deleted:    ../buoi03_250819/first.py
	deleted:    ../buoi03_250819/python101_ST3.ipynb
	deleted:    ../pydata-book

Untracked files:
  (use "git ad

In [25]:
!git add . -n

add 'buoi03_250823/.ipynb_checkpoints/Untitled-checkpoint.ipynb'
add 'buoi03_250823/Untitled.ipynb'
add 'buoi03_250823/pydata-book/'
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint:
hint: 	git submodule add <url> buoi03_250823/pydata-book
hint:
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint:
hint: 	git rm --cached buoi03_250823/pydata-book
hint:
hint: See "git help submodule" for more information.
hint: Disable this message with "git config set advice.addEmbeddedRepo false"


In [26]:
!git add .

hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint:
hint: 	git submodule add <url> buoi03_250823/pydata-book
hint:
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint:
hint: 	git rm --cached buoi03_250823/pydata-book
hint:
hint: See "git help submodule" for more information.
hint: Disable this message with "git config set advice.addEmbeddedRepo false"


In [22]:
# !git status
# !git add . -n
# !git add .
# !git commit -m "buoi03"
# !git push
# !git status
# !git push --force # ép phải commit (nếu xảy ra xung đột)
# !git reset HEAD~  # phục hồi lại trạng thái commit gần nhất

# !git add .
# !git commit -m "buoi03"
# !git push

IndentationError: unexpected indent (2452511960.py, line 2)

In [7]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}

In [8]:
x = [60, 70, 80, 90]
print('len(x)=',len(x))
print('x[0]=',x[0])
print('x[1]=', x[1])
print('x[-1]=',x[-1])
print('x[1:3]=',x[1:3])

len(x)= 4
x[0]= 60
x[1]= 70
x[-1]= 90
x[1:3]= [70, 80]


In [9]:
from IPython.display import display
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
print('c = ')
display(c)

c = 


array([ 4, 10, 18])

In [10]:
import numpy as np

a = np.zeros((2,2))
display(a)

b = np.ones((3,2))
display(b)

c = np.full((4,5),7)
display(c)

d = np.eye(4)
display(d)

e = np.random.random((2,2))
display(e)

array([[0., 0.],
       [0., 0.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[0.47482974, 0.13852077],
       [0.77655479, 0.36530079]])

In [11]:
import numpy as np
a = np.arange(15, dtype=float)
display(a)

a = a.reshape(3,5)
display(a)

display(a.shape)
display(a.ndim)
display(a.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

(3, 5)

2

dtype('float64')

In [12]:
import numpy as np
a = np.array([1,2,3,4,5])
display(a)

array([1, 2, 3, 4, 5])

In [13]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
display(a)
display(a.shape)
display(a.ndim)
display(a.dtype)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

(4, 5)

2

dtype('int64')

In [14]:
a = np.array([
    [0,1,2,3],
    [10,11,12,13],
    [20,21,22,23]
])
display(a)
display(a.shape)
display(a.ndim)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

(3, 4)

2

In [15]:
a = np.arange(1, 10).reshape(3,3)
display(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
display(a[2])
display(a[2].shape)

display(a[2,:])
display(a[2,:].shape)

display(a[2:,:])
display(a[2:,:].shape)

array([7, 8, 9])

(3,)

array([7, 8, 9])

(3,)

array([[7, 8, 9]])

(1, 3)

## Pandas

In [17]:
from IPython.display import display
import pandas as pd
a = pd.DataFrame({
        'a': [4,5,6],
        'b': [7,8,9],
        'c': [10,11,12],
    }, index = [1,2,3])
display(a)
display(a.loc[1])

b = pd.DataFrame([
    {'a':4,'b':7,'c':10},
    {'a':5,'b':8,'c':11},
    {'a':6,'b':9,'c':12},
])
display(b)
display(b.loc[1])

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

a     4
b     7
c    10
Name: 1, dtype: int64

a  b   c
0  4  7  10
1  5  8  11
2  6  9  12

a     5
b     8
c    11
Name: 1, dtype: int64

In [18]:
display(type(a))


pandas.core.frame.DataFrame