## Buổi 03: Phân tích dữ liệu với Python

In [23]:
# !rm -r pydata-book
# !git clone https://github.com/wesm/pydata-book.git
!ls pydata-book/
# !sudo rm -r pydata-book/.git

COPYING     ch02.ipynb	ch06.ipynb  ch10.ipynb	datasets
README.md   ch03.ipynb	ch07.ipynb  ch11.ipynb	examples
appa.ipynb  ch04.ipynb	ch08.ipynb  ch12.ipynb	requirements.txt
appb.ipynb  ch05.ipynb	ch09.ipynb  ch13.ipynb


On branch gh-pages
Your branch is up to date with 'origin/gh-pages'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    ../buoi02_250816/.ipynb_checkpoints/Untitled-checkpoint.ipynb
	deleted:    ../buoi02_250816/.ipynb_checkpoints/ex1_calc-checkpoint.py
	deleted:    ../buoi02_250816/.ipynb_checkpoints/first-checkpoint.py
	deleted:    ../buoi02_250816/Untitled.ipynb
	deleted:    ../buoi02_250816/ex1_calc.py
	deleted:    ../buoi02_250816/ex2_scientific1.ipynb
	deleted:    ../buoi02_250816/ex2_scientific1.txt
	deleted:    ../buoi02_250816/ex4_scientific2.txt
	deleted:    ../buoi02_250816/first.py
	deleted:    ../buoi03_250819/.ipynb_checkpoints/python101_ST3-checkpoint.ipynb
	deleted:    ../buoi03_250819/first.cpp
	deleted:    ../buoi03_250819/first.py
	deleted:    ../buoi03_250819/python101_ST3.ipynb
	deleted:    ../pydata-book

Untracked files:
  (use "git ad

In [27]:
!git add .
    

In [28]:
!git commit -m "buoi03"

[gh-pages 8a6a3f0] buoi03
 3 files changed, 848 insertions(+)
 create mode 100644 buoi03_250823/.ipynb_checkpoints/Untitled-checkpoint.ipynb
 create mode 100644 buoi03_250823/Untitled.ipynb
 create mode 160000 buoi03_250823/pydata-book


In [29]:
!git push

Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 2 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 4.17 KiB | 853.00 KiB/s, done.
Total 6 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/tdung13/ueh25_kythuatlaptrinh_stata_python.git
   28865e6..8a6a3f0  gh-pages -> gh-pages


In [30]:
v = list(range(1, 6))
print(v)
print(2 * v)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [31]:
import numpy as np
v = np.arange(1, 6)
print(v)
print(2 * v)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [32]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}

In [33]:
x = [60, 70, 80, 90]
print(len(x))
print(x[0])
print(x[1])
print(x[-1])

4
60
70
90


In [34]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
print(a)
print(b)
print(c)

[1 2 3]
[4 5 6]
[ 4 10 18]


In [35]:
import numpy as np

# Tạo mảng toàn số 0
a = np.zeros((5, 5))
print("Mảng toàn số 0:\n", a)

# Tạo mảng toàn số 1
b = np.ones((1, 2))
print("Mảng toàn số 1:\n", b)

# Tạo mảng với giá trị cố định là 7
c = np.full((2, 2), 7)
print("Mảng toàn số 7:\n", c)

# Tạo ma trận đơn vị 2x2
d = np.eye(2)
print("Ma trận đơn vị:\n", d)

# Tạo mảng với giá trị ngẫu nhiên từ 0 đến 1
e = np.random.random((2, 2))
print("Mảng ngẫu nhiên:\n", e)

Mảng toàn số 0:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Mảng toàn số 1:
 [[1. 1.]]
Mảng toàn số 7:
 [[7 7]
 [7 7]]
Ma trận đơn vị:
 [[1. 0.]
 [0. 1.]]
Mảng ngẫu nhiên:
 [[0.03877065 0.72286845]
 [0.07247194 0.76603248]]


In [36]:
import numpy as np
a = np.arange(15)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

a = a.reshape(3,5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)
1
int64
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64


In [37]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [38]:
b = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [39]:
b = np.array([
    [0,1,2,3],
    [10,11,12,13],
    [20,21,22,23],
])
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
2
(3, 4)
int64


In [40]:
a = np.arange(9).reshape(3,3)
print(a)
print(a[:2,1:], a[:2,1:].shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2]
 [4 5]] (2, 2)


## Pandas

In [41]:
import pandas as pd
from IPython.display import display

df = pd.DataFrame({
        "a": [4, 5, 6],
        "b": [7, 8, 9],
        "c": [10, 11, 12]
    },
        index = [1, 2, 3])

display(df)
display(df['a'])
display(df.loc[2])

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

1    4
2    5
3    6
Name: a, dtype: int64

a     5
b     8
c    11
Name: 2, dtype: int64

In [42]:
type(df)

pandas.core.frame.DataFrame

In [43]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print('pandas imported')

pandas imported


In [44]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [45]:
dates = pd.date_range('20181001', periods=6)
dates

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [46]:
s


0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [47]:
df_a = pd.DataFrame(
    {'A': pd.Series([1,3,5,np.nan,6,8])}, 
    dtype=float)
df_a

A
0  1.0
1  3.0
2  5.0
3  NaN
4  6.0
5  8.0

In [48]:
df = pd.DataFrame(
    np.random.randn(6,4), 
    index=dates, 
    columns=list('ABCD'))
df

A         B         C         D
2018-10-01  1.247050 -1.404583  0.001364  0.970262
2018-10-02  0.020442  0.173448 -0.657651  2.609442
2018-10-03  0.317607 -1.907332  0.390034 -0.777304
2018-10-04  0.040511 -0.645765 -1.167925 -0.284365
2018-10-05 -0.477186 -0.030148  0.094505 -0.471058
2018-10-06 -0.133494 -0.862868  1.355430 -1.672548

In [49]:
df = pd.DataFrame(
    np.random.randn(3,5), 
    index=['student1','student2','student3'], 
    columns=list('ABCDE'))
df

A         B         C         D         E
student1 -0.136698 -1.464438 -1.383975 -0.398557  0.521484
student2  0.115780  1.272647 -0.816136 -0.600388 -0.264244
student3 -0.931901  0.711288  1.165205 -1.258365 -0.085314

In [50]:
df2 = pd.DataFrame(
    { 
        'A' : 1.,
        'B' : pd.Timestamp('20181001'),
        'C' : pd.Series(2.5,index=list(range(4)),dtype='float32'),
        'D' : np.array([3] * 4,dtype='int32'),
        'E' : pd.Categorical(["test","train","test","train"]),
        'F' : 'foo' })
df2

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [51]:
df3 = pd.DataFrame(
    [
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'test', 'F': 'foo'},
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'train', 'F': 'foo'},
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'test', 'F': 'foo'},
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'train', 'F': 'foo'}
    ]
)
df3

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

## Kết thúc